### ISSUE TITLE
mqtt topic 

### ISSUE THREAD

**Issue by Egyras** [LukasdeBoer/esp8266-whr930-mqtt#1]
Hi, for what purpose is used this mqtt topic ? mqtt_get_update_topic = "house/ventilation/whr930/update"

**Comment by LukasdeBoer** [comment]
Hi!! I'm sorry, I didn't get notifications for new issues opened so I only just saw this. That is a topic that I used during development. If you send a message to that topic, it will query the whr930 for new information. It's not necessary because we do it in a loop now.
