### ISSUE TITLE
Cannot set fan level

### ISSUE THREAD

**Issue by geojoh** [LukasdeBoer/esp8266-whr930-mqtt#2]
Hi, I own a Zehnder ComfoD 350 which has pretty much the same controller board as the WHR930. I am connected to it via the RJ45/RS232 connected to an ESP8266 and can see all the data via MQTT explorer. The setup is connected to Home Assistant. The problem is that I cannot set any of the values changeable parameters fan level, temperature. I have tried changing the values also directly via the mqtt broker, but it does not change anything. 
The system has a perilex/rotary switch with 4 positions (0,1,2,3), so I put the system on level 1 and tried again, but no luck.  I saw somebody was reporting a similar issue here:

https://github.com/Mosibi/whr_930/issues/1

Is perhaps the protocol different? 
Any help appreciated. Thank you!

**Comment by Egyras** [comment]
@LukasdeBoer  I believe its possible can be issues if mqtt message arrives for topics like fan speed set and etc... and you get loop update_everything();
Its better to make a call update_everything, then check if no any new mqtt message which needs to change settings. If nothing to do call update_everyhing else execute mqtt message. Or its bad idea?

**Comment by LukasdeBoer** [comment]
Hi Geojoh,

Is there anything you can see in the debug log? Listen to house/ventilation/whr930/log with your mqtt explorer and see what it logs when you try to change the ventilation.

> @LukasdeBoer I believe its possible can be issues if mqtt message arrives for topics like fan speed set and etc... and you get loop update_everything();
> Its better to make a call update_everything, then check if no any new mqtt message which needs to change settings. If nothing to do call update_everyhing else execute mqtt message. Or its bad idea?

Yeah, that's a great idea. That's exactly how the followup software I use is written. It's not really mergable here because it combines communication with other appliances I have in the same room (solar inverter, heat pump) in one application. You can see the structure here: https://github.com/timjong93/growatt_mqtt/blob/feature/integration/growatt_mqtt/growatt_mqtt.ino#L526

Feel free to make a PR with such functionality!

**Comment by geojoh** [comment]
Hi,

Thanks for the feedback and sorry for getting back with some delay. I re-hooked the whole cabling as I thought there might be some issues there, but after triple checking the connection, the result are the same - I can read values but not set anything.
Connection looks like this: RS232 port > RJ45 cable to DB9 connector > (pin 2 to pin 2, pin 3 to 3, pin 8 to 5) > MAX3232 to ESP8266 (TX to TX, RX to RX, GND to GND, VCC to VU 5v) I also tried TX to RX and RX to TX but then I get no readings.

Just to be sure, the perilex (4 positions) switch can be kept, right? There is no need to touch that part and it is not overwriting physically the rs232 commands?
I ran a debug on the mqtt and I can see the commands reaching the mqtt, when triggered from home assistant.
In the example below I tried to change the temperature. The last value on the bottom shows 25 for set_temperature but the comfort_temp=20 still remains un-changed. The same is valid for ventilation speed.
Any hints what else I should try? Thank you

filter_state = Ok
comfort_temp = 20.00
outside_air_temp = 4.50
supply_air_temp = 18.00
return_air_temp = 21.50
exhaust_air_temp = 8.00
return_air_level = 40.00
supply_air_level = 40.00
ventilation_level = 1
intake_fan_active = Yes
intake_fan_speed = 40.00
exhaust_fan_speed = 40.00
valve_bypass_percentage = 0
valve_preheating = 0
bypass_motor_current = 0
preheating_motor_current = 191
bypass_factor = 0
bypass_step = 5
bypass_correction = 0
summermode = No
set_temperature = 25

**Comment by LukasdeBoer** [comment]
Could you clarify what you mean with the perilex? Perhaps a photo? I am not sure what you mean by that and I think that might be where our setup differs.

**Comment by MJPVDH** [comment]
> Hi,
> 
> Thanks for the feedback and sorry for getting back with some delay. I re-hooked the whole cabling as I thought there might be some issues there, but after triple checking the connection, the result are the same - I can read values but not set anything.
> Connection looks like this: RS232 port > RJ45 cable to DB9 connector > (pin 2 to pin 2, pin 3 to 3, pin 8 to 5) > MAX3232 to ESP8266 (TX to TX, RX to RX, GND to GND, VCC to VU 5v) I also tried TX to RX and RX to TX but then I get no readings.
> 
> Just to be sure, the perilex (4 positions) switch can be kept, right? There is no need to touch that part and it is not overwriting physically the rs232 commands?
> I ran a debug on the mqtt and I can see the commands reaching the mqtt, when triggered from home assistant.
> In the example below I tried to change the temperature. The last value on the bottom shows 25 for set_temperature but the comfort_temp=20 still remains un-changed. The same is valid for ventilation speed.
> Any hints what else I should try? Thank you
> 
> filter_state = Ok
> comfort_temp = 20.00
> outside_air_temp = 4.50
> supply_air_temp = 18.00
> return_air_temp = 21.50
> exhaust_air_temp = 8.00
> return_air_level = 40.00
> supply_air_level = 40.00
> ventilation_level = 1
> intake_fan_active = Yes
> intake_fan_speed = 40.00
> exhaust_fan_speed = 40.00
> valve_bypass_percentage = 0
> valve_preheating = 0
> bypass_motor_current = 0
> preheating_motor_current = 191
> bypass_factor = 0
> bypass_step = 5
> bypass_correction = 0
> summermode = No
> set_temperature = 25

Did you get it done?  I can change the temperature and ventilation setting but the WHR930 WTW is not responding!

**Comment by rnldnkp** [comment]
Did anyone manage to fix this? 

Besides the "_" typo in the homeassist/.ino code the MQTT topic 'setventilation' does show in the log output, but does not actually change anything.

**Comment by CommanderTux** [comment]
@LukasdeBoer, @rnldnkp ,

When I changed the topics in the automation part to

```
topic: house/ventilation/whr930/setventilation
topic: house/ventilation/whr930/settemperature
```


It just works. Maybe you could change the topics in the **esp8266-whr930-mqtt.ino**

**Comment by LukasdeBoer** [comment]
Well spotted @CommanderTux , thanks. Fixed the documentation!
