### ISSUE TITLE
lovelace UI config

### ISSUE THREAD

**Issue by TimvdEijnden** [LukasdeBoer/esp8266-whr930-mqtt#3]
@LukasdeBoer 

Do you mind sharing your entries in ui-lovelace.yaml ? 

They are not in the readme.

It would be great if you would add them, thanks!

**Comment by LukasdeBoer** [comment]
Hi Tim,

For the custom lovelace card, you can follow the instructions in https://github.com/timjong93/lovelace-wtw :)

**Comment by TimvdEijnden** [comment]
No I meant what's shown on this image:

https://github.com/LukasdeBoer/esp8266-whr930-mqtt/blob/master/homeassistant.png

**Comment by LukasdeBoer** [comment]
Oh, that's just a regular 'entities' list in lovelace. :D

**Comment by Jeffreyvanesch** [comment]
For some reason I can't seem to add these entities in lovelace, 
Using the + icon and choosing entity none of the entities are showing up, I've copied and pasted the config lines from the post into my configuration.yaml but cannot seem to get it to work.

The same with the custom lovelace card. MQTT's communication is working as expected when subscribed to the /# topic i can see the messages parsing trough.

**Comment by LukasdeBoer** [comment]
Did you add all the mqtt sensors at the bottom of the readme?

**Comment by Jeffreyvanesch** [comment]
Yes, I did.
Copied all the sensors listed in the readme into my config.yaml.
What surprises me is that now I only have the automations 'automation.temperature_level_slider_moved_in_gui' 'automation.ventilation_level_slider_moved_in_gui' and 'input_number.set_wtw_temperature' available. Using the pin out listed in the same file I can see the messages being received into hass, but no extra entities are shown.

Before a DB failure i had the card listed available but no adequate values where parsed.

**Comment by LukasdeBoer** [comment]
Did you configure the mqtt integration properly? Can you follow the topics in homeassistant?

**Comment by Jeffreyvanesch** [comment]
I've followed the steps in the hass topics, Still no change.
Could the cause be that some entries in your configuration lines are showing up multiple times, Hassio trows several errors about this:
6:06:39 PM – Hass.io (ERROR)
YAML file /config/configuration.yaml contains duplicate key "group". Check lines 20 and 179.
6:06:39 PM – util/yaml/loader.py (WARNING)
YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 77 and 174.
6:06:39 PM – util/yaml/loader.py (WARNING)
YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 26 and 77.
6:06:39 PM – util/yaml/loader.py (WARNING)
YAML file /config/configuration.yaml contains duplicate key "input_number". Check lines 59 and 68.`

**Comment by TimvdEijnden** [comment]
@Jeffreyvanesch I had to make some adjustments in order to get it to work. I'll can post my config later.

**Comment by LukasdeBoer** [comment]
Could you make a PR? :-)

**Comment by Jeffreyvanesch** [comment]
@LukasdeBoer I can't create a PR request since it's greyed out.
Will continue with this in a new issue to retain the overview.

**Comment by Jeffreyvanesch** [comment]
@TimvdEijnden Would you mind sharing your config for the WHR in #4  ?

**Comment by TimvdEijnden** [comment]
@Jeffreyvanesch 

https://gist.github.com/TimvdEijnden/80d5019513a4a2074be33092845a49de

**Comment by Jeffreyvanesch** [comment]
Got the sensors showing again, But unfortunately the data still isn't being processed.
The MQTT messages are successfully being received into HA.
